### ISSUE TITLE
ActionView::Template::Error (undefined method `workspace_id' )

### ISSUE THREAD

**Issue by kaitaku** [fredsdc/redmine_web_forms#1]
ActionView::Template::Error (undefined method `workspace_id' for #<Project:0x000000010e46e560>):
    26:   <td class="status"><%= webform.issue_status %></td>
    27:   <td class="group"><%= webform.group %></td>
    28:   <td class="role"><%= webform.role %></td>
    29:   <td><%= checked_image webform.validate_webform(nil) %></td>
    30:   <td class="buttons">
    31:     <%= link_to l(:button_view), webform_path(webform.identifier), {:class => 'icon icon-document'}  %>
    32:     <%= delete_link webform_path(webform) %>

**Comment by fredsdc** [comment]
Workspace is a customization for the Redmine I use. I removed it on the main branch. Fixed it and the missing helper (it did not give me errors because of some other plugin).

Main branch should work now, please test.

Thanks for reporting.
