### ISSUE TITLE
How can I format the question description?

### ISSUE THREAD

**Issue by ntelogo** [fredsdc/redmine_web_forms#12]
Are there any tags I can use to format the question description? e.g. how do I add a new line?

**Comment by fredsdc** [comment]
I didn't implement formatting of questions, but I think it is possible. Todo.

new line=ctrl-n

**Comment by fredsdc** [comment]
Oops, new lines are shift-enter, but they don't transpose to the show method. You can still javascript format them, but it is not easy.
Text is included on the field label, I would have to put it in a separate div.wiki. It is a different format, but feasible.

**Comment by fredsdc** [comment]
Updated. Now you can use md tags in questions. Please update and report.

**Comment by ntelogo** [comment]
Awesome! Thank you so much for responding to this so promptly! 
I will test and get back with  feedback.

**Comment by ntelogo** [comment]
Updating the plugin has resulted in internal errors on all webform submission pages.

Attaching the log.
[webforms error log entries.txt](https://github.com/user-attachments/files/16522557/webforms.error.log.entries.txt)

**Comment by ntelogo** [comment]
Environment:
  Redmine version                4.2.4.stable
  Ruby version                   2.7.4-p191 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  5.2.6.2

**Comment by fredsdc** [comment]
It is a Ruby/Rails version problem. I'll try using textilizable instead, please wait.

**Comment by fredsdc** [comment]
Updated. Would you please try again?

**Comment by fredsdc** [comment]
One more update. Textilize was allowing me to use html tags to mark a red * in required fields, I'll have to look how to do it with textilizable. Returned to a black * for now.

**Comment by ntelogo** [comment]
Hey, 
Much appreciated! It is now working!

Apologies for the late reply. I'm not managing our server, thus it usually takes some time for our tech to resolve submitted tickets.
