### ISSUE TITLE
Error webform - ActionView::Template::Error (undefined method `allow_attachments' for #<Webform:0x00007f33660a2828>):

### ISSUE THREAD

**Issue by thiagoinacioalves** [fredsdc/redmine_web_forms#5]
<html>
<body>

Rendering plugins/redmine_web_forms/app/views/webforms/new.html.erb within layouts/base
--
  | Rendered plugins/redmine_web_forms/app/views/webforms/_options.html.erb (5.9ms)
  | Rendered plugins/redmine_web_forms/app/views/webforms/_form.html.erb (9.3ms)
  | Rendered plugins/redmine_web_forms/app/views/webforms/new.html.erb within layouts/base (10.1ms)
  | Completed 500 Internal Server Error in 25ms (ActiveRecord: 7.7ms)
  |  
  | ActionView::Template::Error (undefined method `allow_attachments' for #<Webform:0x00007f33660a2828>):
  | 3: <p><%= f.select :project_id, project_tree_options_for_select(@projects, :selected => @webform.project), {:include_blank => true}, :onchange => "updateFields();" %></p>
  | 4: <p><%= f.select :tracker_id, options_for_select(@trackers, :selected => @webform.tracker_id), {:include_blank => true}, :onchange => "updateFields();" %></p>
  | 5: <p><%= f.select :issue_status_id, options_for_select(@statuses, :selected => @webform.issue_status_id), {:include_blank => true, :label => :label_issue_status} %></p>
  | 6: <p><%= f.check_box :allow_attachments %></p>
  | 7: <% end %>
  |  
  | lib/redmine/views/labelled_form_builder.rb:36:in `check_box'
  | plugins/redmine_web_forms/app/views/webforms/_options.html.erb:6:in `block in _plugins_redmine_web_forms_app_views_webforms__options_html_erb___3509738169220588794_69929359749660'
  | app/helpers/application_helper.rb:1466:in `labelled_fields_for'
  | plugins/redmine_web_forms/app/views/webforms/_options.html.erb:1:in `_plugins_redmine_web_forms_app_views_webforms__options_html_erb___3509738169220588794_69929359749660'
  | plugins/redmine_web_forms/app/views/webforms/_form.html.erb:9:in `_plugins_redmine_web_forms_app_views_webforms__form_html_erb___2896762973596867207_69929358653280'
  | plugins/redmine_web_forms/app/views/webforms/new.html.erb:8:in `block in _plugins_redmine_web_forms_app_views_webforms_new_html_erb___2159188331258433418_69929359434300'
  | app/helpers/application_helper.rb:1459:in `labelled_form_for'
  | plugins/redmine_web_forms/app/views/webforms/new.html.erb:7:in `_plugins_redmine_web_forms_app_views_webforms_new_html_erb___2159188331258433418_69929359434300'

</body>
</html>

**Comment by fredsdc** [comment]
Hello,

I forgot to include a migrations file in the main branch. I fixed it early today, if you have just updated the plugin, you have to migrate the database (to create this allow_attachemnts column on the Webform table):

git pull
bundle exec rake redmine:plugins:migrate NAME=redmine_web_forms

Sorry and thank you for reporting.

**Comment by thiagoinacioalves** [comment]
thank you, for your help! it all worked out now.
