### ISSUE TITLE
How to remove that were added incorrectly?

### ISSUE THREAD

**Issue by Jongsic** [fredsdc/redmine_web_forms#8]
Thank you for updating the information regarding Redmine 5 support.

I have a few questions:

1. I would like to know how to delete Custom Fields or Questions that were added incorrectly.
2. When using a Question as a text input and setting it as Required, an error occurs even when the form input is given.
3. What is the best practice for generating the subject and description of a new issue based on the answers from webform? I have tried various attempts in the onsubmit event, but it hasn't been successful.

And during the installation, I encountered conflict with the table name between RedmineUp's Question plugin and the existing table named "question." 
I have temporarily removed the question plugin and I am currently testing.

However, it would be more beneficial if you consider adding a prefix to the table name for better integration (e.g: "webform_questions").
Thank you for your understanding.

**Comment by fredsdc** [comment]
1. There's a delete trashcan icon after each Question/Custom Field. Just checked with Redmine 5.0.
2. It was a bug. This situation didn't occur to me when coding. Fixed. Please update. Thank you.
3. Create question fields assigned to description/subject, give each a unique identifier, mark them hidden. Code javascript to fill them up.
4. I don't have RedmineUp's Question, but maybe there are more conflicts, I'll try to check.

**Comment by fredsdc** [comment]
Renamed table Question to WebformQuestion and similar possible conflicts. Maybe it's working with RedmineUp's Question plugin now.

**Comment by fredsdc** [comment]
Just crarifying: the trashcan icon should be imediately after the question/custom_field title, for example:
Question 1 `<trashcan icon>`
  `<question 1 properties>`
Question 2 `<trashcan icon>`
  `<question 2 properties>`

In the html:
`<legend>Question <span class="number">1</span> <img class="delete icon-only icon-del" title="Delete" onclick="$(this).parent().parent().remove(); renumber_list();"></legend>`

**Comment by fredsdc** [comment]
3. Here's a working example of onsubmit javascript (it concatenates the content of a question with identifier tdb and the author name):
`$('#subject').val($('#tdb').val() + " - " + $('#author_name').val());`

where:
  * "subject" is the identifier for the subject hidden field
  * "tdb" is the identifier of another field
